/* ============================================================
   BEYOND THE REACH
   Episode 1 — "Raise Your Colors"      target runtime 23:00

   Beat keys
     sc    scene id (Art.SCENES)          shot  wide|mid|cu|ecu|two|insert|ots
     who   speaker id                     line  dialogue
     em    emotion (face + voice acting)  d     planned seconds
     act   action line (no dialogue)      card  location card
     cam   {z,x,y,rot} camera pose        to    camera pose to drift toward
     fx    extra particle systems         sfx   ['name'] or [['name',delay]]
     mus   music cue                      amb   ambience override
     shake flash speed  one-shot punctuation
     title {l1,l2,sub} full-screen card   chap  chapter marker
   ============================================================ */
const EPISODE = {
  show: 'BEYOND THE REACH',
  num: 1,
  title: 'RAISE YOUR COLORS',
  runtime: 1380,

  synopsis:
    'Eight years ago a dying pirate gave a nine-year-old a compass that does not point north. ' +
    'Today the Concord comes to Saltmarrow to collect, a ship with no colors slides into the harbour, ' +
    'and Rook Vantier finally says the sentence out loud.',

  beats: [

/* ══════════════════════ COLD OPEN ══════════════════════ */
{ chap: 'Cold Open' },
{ sc:'void', shot:'wide', d:4.5, mus:'wonder', act:'Black. Water moving somewhere close.' },
{ sc:'void', shot:'wide', who:'vo', em:'soft', d:4.4,
  line:"They teach you that the sea has an edge." },
{ sc:'reach_dawn', shot:'wide', d:7.0, card:'THE REACH', mus:'wonder', cam:{z:1.06}, to:{z:1.0},
  sfx:[['gull',1.2]], who:'vo', em:'soft',
  line:"Not a metaphor. An edge." },
{ sc:'reach_dawn', shot:'wide', d:8.2, cam:{z:1.0,x:-.06}, to:{z:1.12,x:.04}, who:'vo', em:'calm',
  line:"Two hundred miles west of anywhere, the water stands up and refuses to lie back down." },
{ sc:'reach_dawn', shot:'mid', d:7.6, cam:{z:1.3,y:-.05}, to:{z:1.42,y:-.02}, who:'vo', em:'calm',
  line:"A wall of cold light from the ice in the north to the ice in the south. It does not move. It does not break." },
{ sc:'reach_dawn', shot:'wide', d:5.4, cam:{z:1.42}, to:{z:1.0}, who:'vo', em:'flat',
  line:"And it does not let anybody through." },
{ sc:'reach_dawn', shot:'wide', d:6.2, who:'vo', em:'dry',
  line:"The Concord calls it the mercy of God. They put it on the money, so you know they mean it." },
{ sc:'reach_dawn', shot:'wide', d:6.8, cam:{z:1.0}, to:{z:1.08}, who:'vo', em:'soft',
  line:"Every child in Saltmarrow learns the same three words before they learn to swim. The sea ends." },
{ sc:'storm_sea', shot:'wide', d:5.2, mus:'dread', sfx:['thunder'], flash:.5, who:'vo', em:'flat',
  line:"I was nine the night I learned that was a lie." },

{ sc:'storm_sea', shot:'wide', d:5.0, card:'EIGHT YEARS AGO', mus:'dread', sfx:[['thunder',1.4]],
  act:'A storm with teeth. Somewhere out in it, cannon fire walks across the water like a man counting.' },
{ sc:'storm_sea', shot:'wide', d:4.2, sfx:['cannon'], shake:.9, flash:.35,
  act:'Three lights bloom on the horizon. Then the sound arrives.' },
{ sc:'burning_ship', shot:'wide', d:5.6, mus:'dread', sfx:[['cannon',.2],['creak',2.2]], shake:.7,
  act:'A ship is burning down to her ribs.' },
{ sc:'burning_ship', shot:'mid', d:5.0, cam:{z:1.5,y:-.12}, to:{z:1.62,y:-.14}, sfx:['flagsnap'],
  act:'A black flag goes up her mainmast. Nobody raises a flag while they are sinking unless they mean it as an argument.' },
{ sc:'burning_ship', shot:'wide', d:4.0, sfx:['cannon'], shake:1, flash:.55,
  act:'The Concord answers the argument.' },

{ sc:'rocks_night', shot:'wide', d:5.4, mus:'grief', card:'SALTMARROW — THE ROCKS BELOW THE LIGHT',
  act:'A boy of nine on the black rocks, soaked to the bone, holding a lantern he was told not to take.' },
{ sc:'rocks_night', shot:'mid', d:4.6, cam:{z:1.35}, to:{z:1.5},
  act:'Something in the surf that is the wrong shape for driftwood.' },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'dying', d:4.0, chars:[{id:'hallow',x:.5,y:.62,s:1}],
  line:"Don't. Don't call for them, boy." },
{ sc:'rocks_night', shot:'cu', who:'rook', em:'fear', d:3.4, chars:[{id:'rook',x:.5,y:.62,s:.88}],
  line:"You're bleeding. Everywhere." },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'dry', d:5.6,
  line:"Yes. I've been at it a while now. I'd rather like to finish in private." },
{ sc:'rocks_night', shot:'cu', who:'rook', em:'urgent', d:3.6,
  line:"There's soldiers coming down the cliff road." },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'tired', d:3.6,
  line:"Then we'd best be quick and unsentimental." },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'soft', d:3.0,
  line:"Hold out your hand." },
{ sc:'rocks_night', shot:'insert', d:5.2, mus:'mystery', sfx:['bell'], cam:{z:1.9}, to:{z:1.7},
  act:'A brass compass, warm from a dying man, heavier than brass has any business being.' },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'calm', d:3.4,
  line:"That doesn't point north." },
{ sc:'rocks_night', shot:'cu', who:'rook', em:'awe', d:3.2,
  line:"Then what's it point at?" },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'soft', d:6.6,
  line:"Whatever you'd die for. It's an honest instrument. That's the cruel part." },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'determined', d:6.0,
  line:"So don't you open it. Not until you're old enough to survive the answer." },
{ sc:'rocks_lanterns', shot:'wide', d:4.6, mus:'tension', sfx:['creak'],
  act:'Lantern light comes down the cliff path in an orderly line. Whatever else the Concord is, it is orderly.' },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'dry', d:3.2,
  line:"Ah. That'll be the time." },
{ sc:'rocks_night', shot:'cu', who:'rook', em:'fear', d:3.0,
  line:"Where are you going?" },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'grin', d:3.0,
  line:"To be loud." },
{ sc:'rocks_night', shot:'mid', d:4.2, cam:{z:1.2}, to:{z:1.05},
  act:'He gets up. It costs him most of what he has left.' },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'warm', d:3.2,
  line:"Boy. What do they call you?" },
{ sc:'rocks_night', shot:'cu', who:'rook', em:'soft', d:2.6,
  line:"Rook." },
{ sc:'rocks_night', shot:'cu', who:'hallow', em:'warm', d:5.4,
  line:"Rook. Good. Birds do all right out here." },
{ sc:'rocks_lanterns', shot:'wide', d:5.0, mus:'grief', cam:{z:1.0}, to:{z:1.14},
  act:'He walks up the beach toward the lanterns with his hands open and empty.' },
{ sc:'rocks_lanterns', shot:'wide', who:'hallow', em:'roar', d:4.4,
  line:"EVENING, GENTLEMEN! I'M THE ONE YOU CAME FOR!" },
{ sc:'rocks_lanterns', shot:'wide', d:2.2, sfx:['musket'], flash:.75, shake:.8, act:'' },
{ sc:'void', shot:'wide', d:4.2, mus:null, sfx:[['musket',.15],['musket',.32]],
  act:'The boy does not look. He is nine, and he keeps his eyes shut, and he holds the compass so hard it leaves a mark he still has.' },
{ sc:'void', shot:'wide', who:'vo', em:'flat', d:6.4, mus:'grief',
  line:"They never found the body. They never found the ship." },
{ sc:'void', shot:'wide', who:'vo', em:'soft', d:5.0,
  line:"And for eight years, I never opened the compass." },
{ sc:'void', shot:'wide', who:'vo', em:'dry', d:6.0,
  line:"Which — I want to be clear about this — was not restraint. That was fear." },
{ sc:'saltmarrow_dawn', shot:'wide', d:5.8, mus:'hope', flash:.85, sfx:['gull'], cam:{z:1.18}, to:{z:1.0},
  who:'vo', em:'grin', line:"I got over it." },

/* ══════════════════════ OPENING ══════════════════════ */
{ chap:'Opening', op:true },
{ sc:'reach_night', shot:'wide', d:4.0, mus:'op', op:1, cam:{z:1.3}, to:{z:1.0},
  title:{l1:'', l2:'', sub:''} },
{ sc:'open_sea_dawn', shot:'wide', d:3.4, op:1, cam:{z:1.0,x:.08}, to:{z:1.1,x:-.05}, sfx:['whoosh'] },
{ sc:'roofs_night', shot:'wide', d:3.0, op:1, cam:{z:1.25,x:-.1}, to:{z:1.05,x:.1},
  chars:[{id:'rook',x:.42,y:.72,s:.6,fig:1,pose:'reach'}] },
{ sc:'rocks_night', shot:'insert', d:2.6, op:1, cam:{z:1.8,rot:-4}, to:{z:1.5,rot:2} },
{ sc:'reach_dawn', shot:'wide', d:3.2, op:1, cam:{z:1.4}, to:{z:1.0}, flash:.3 },
{ sc:'black', shot:'wide', d:4.6, op:1, flash:.9, sfx:['stinger'],
  title:{l1:'BEYOND', l2:'THE REACH', sub:''} },
{ sc:'saltmarrow_dawn', shot:'cu', d:3.4, op:1, chars:[{id:'rook',x:.5,y:.6,s:1,em:'grin'}],
  title:{l1:'', l2:'', sub:'ROOK VANTIER'} },
{ sc:'docks_day', shot:'cu', d:3.2, op:1, chars:[{id:'nell',x:.5,y:.6,s:1,em:'dry'}], sfx:['clash'],
  title:{l1:'', l2:'', sub:'NELL OSTRAND'} },
{ sc:'harbor_night', shot:'cu', d:3.2, op:1, chars:[{id:'thorne',x:.5,y:.6,s:1,em:'tease'}], sfx:['flagsnap'],
  title:{l1:'', l2:'', sub:'CAPTAIN IRIS THORNE'} },
{ sc:'concord_deck', shot:'cu', d:3.2, op:1, chars:[{id:'ardent',x:.5,y:.6,s:1,em:'cold'}],
  title:{l1:'', l2:'', sub:'COMMODORE VESK ARDENT'} },
{ sc:'open_sea_dawn', shot:'wide', d:3.4, op:1, cam:{z:1.16,y:.06}, to:{z:1.0,y:0}, sfx:['splash'] },
{ sc:'gull_deck', shot:'wide', d:3.0, op:1, chars:[
    {id:'grit',x:.24,y:.7,s:.55,fig:1},{id:'thorne',x:.5,y:.68,s:.55,fig:1,pose:'point'},{id:'nell',x:.74,y:.7,s:.5,fig:1}] },
{ sc:'storm_sea', shot:'wide', d:3.0, op:1, sfx:['cannon'], shake:.7, flash:.3 },
{ sc:'burning_ship', shot:'wide', d:2.6, op:1, cam:{z:1.3,rot:3}, to:{z:1.1,rot:-2} },
{ sc:'dock_confront', shot:'two', d:3.4, op:1, speed:1,
  chars:[{id:'rook',x:.32,y:.66,s:.9,em:'shout'},{id:'ardent',x:.68,y:.66,s:.9,em:'cold',flip:1}] },
{ sc:'rocks_night', shot:'cu', d:2.8, op:1, chars:[{id:'hallow',x:.5,y:.6,s:1,em:'warm',back:0}], mus:'op' },
{ sc:'seacave', shot:'wide', d:5.2, op:1, cam:{z:1.0}, to:{z:1.16},
  chars:[{id:'rook',x:.4,y:.78,s:.5,fig:1}] },
{ sc:'reach_night', shot:'wide', d:4.0, op:1, cam:{z:1.0,y:.05}, to:{z:1.22,y:-.03} },
{ sc:'gull_deck_flag', shot:'wide', d:4.2, op:1, sfx:['flagsnap'], flash:.4, cam:{z:1.4}, to:{z:1.0} },
{ sc:'open_sea_dawn', shot:'wide', d:4.6, op:1, cam:{z:1.0}, to:{z:1.1},
  chars:[{id:'rook',x:.3,y:.74,s:.55,fig:1,pose:'reach'},{id:'nell',x:.46,y:.76,s:.5,fig:1},
         {id:'thorne',x:.62,y:.74,s:.55,fig:1},{id:'grit',x:.78,y:.76,s:.6,fig:1}] },
{ sc:'black', shot:'wide', d:6.2, op:1, flash:.7, sfx:['stinger'],
  title:{l1:'BEYOND', l2:'THE REACH', sub:'EPISODE 1 · RAISE YOUR COLORS'} },

/* ══════════════════════ PART A ══════════════════════ */
{ chap:'Part A' },
{ sc:'saltmarrow_dawn', shot:'wide', d:7.0, mus:'warm', card:'SALTMARROW — THE LAST LEGAL PORT',
  sfx:[['bell',.4],['gull',2.6]], cam:{z:1.1,x:-.05}, to:{z:1.0,x:.03},
  act:'Six hundred people, one lighthouse, and a rule about how far out you are allowed to love the water.' },
{ sc:'docks_day', shot:'wide', d:5.4, mus:'warm', sfx:['gull'], cam:{z:1.0}, to:{z:1.06},
  act:'Morning on the loading dock. Rope, fish, shouting, and one boy doing something with a cargo net that the net was not designed for.' },
{ sc:'docks_day', shot:'wide', d:3.2, sfx:['whoosh'], speed:.9, cam:{z:1.3,y:-.08}, to:{z:1.0,y:.04},
  chars:[{id:'rook',x:.55,y:.6,s:.5,fig:1,pose:'reach'}], act:'' },
{ sc:'docks_day', shot:'cu', who:'nell', em:'flat', d:2.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Rook." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'grin', d:2.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Morning!" },
{ sc:'docks_day', shot:'cu', who:'nell', em:'dry', d:3.2,
  line:"That is a two-hundred-pound net." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'grin', d:5.0,
  line:"It's a two-hundred-pound net going down. Gravity's doing most of the work." },
{ sc:'docks_day', shot:'cu', who:'nell', em:'dry', d:4.4,
  line:"Gravity's doing all of the work. That's the part I'd think about." },
{ sc:'docks_day', shot:'wide', d:3.0, sfx:['wood'], shake:.5, chars:[{id:'rook',x:.55,y:.72,s:.5,fig:1}],
  act:'He lands the way a sack of something lands.' },
{ sc:'docks_day', shot:'cu', who:'rook', em:'breathless', d:3.0,
  line:"Stuck it." },
{ sc:'docks_day', shot:'cu', who:'nell', em:'flat', d:2.6,
  line:"You did not." },
{ sc:'docks_day', shot:'two', d:4.6, mus:'warm',
  chars:[{id:'nell',x:.36,y:.64,s:.86},{id:'rook',x:.66,y:.66,s:.86,flip:1}],
  act:'Nell Ostrand, eighteen, keeps the crane running and the town honest about physics.' },
{ sc:'docks_day', shot:'cu', who:'nell', em:'flat', d:4.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Sanctity's on the horizon. It's Tithe Day." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'bitter', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Already?" },
{ sc:'docks_day', shot:'cu', who:'nell', em:'cold', d:5.2,
  line:"Third time this year. Third. They only come that often when they're nervous." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'dry', d:3.6,
  line:"What's an empire got to be nervous about?" },
{ sc:'docks_day', shot:'cu', who:'nell', em:'flat', d:3.4,
  line:"Ask it. See what it says." },

{ sc:'market_day', shot:'wide', d:5.2, mus:'warm', amb:['crowd'], sfx:['gull'], cam:{z:1.05,x:.05}, to:{z:1.0,x:-.04},
  card:'THE FISH ROW',
  act:'The market smells like the inside of the sea. Mama Dol has been gutting the same shape of fish for fifty years.' },
{ sc:'market_day', shot:'cu', who:'dol', em:'dry', d:3.2, chars:[{id:'dol',x:.5,y:.6,s:1}],
  line:"You're late, sunshine." },
{ sc:'market_day', shot:'cu', who:'rook', em:'grin', d:4.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I'm never late. I'm early for a thing that happens later." },
{ sc:'market_day', shot:'cu', who:'dol', em:'flat', d:2.6,
  line:"Take the crate." },
{ sc:'market_day', shot:'two', d:4.2, chars:[{id:'dol',x:.34,y:.64,s:.86},{id:'rook',x:.66,y:.64,s:.86,flip:1}],
  act:'He takes the crate. He always takes the crate. It is the closest thing this town has to a family arrangement.' },
{ sc:'market_day', shot:'cu', who:'dol', em:'warm', d:5.6, chars:[{id:'dol',x:.5,y:.6,s:1}],
  line:"Your mother used to carry that same crate. Badly. You've got her wrists." },
{ sc:'market_day', shot:'cu', who:'rook', em:'soft', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"That a compliment?" },
{ sc:'market_day', shot:'cu', who:'dol', em:'dry', d:3.0,
  line:"It's a diagnosis." },

{ sc:'square_tithe', shot:'wide', d:6.0, mus:'dread', amb:['crowd','wind'], sfx:['bell'],
  cam:{z:1.0}, to:{z:1.08}, card:'TITHE DAY',
  act:'And then the light in the square changes, because something white and enormous has come between the town and the sun.' },
{ sc:'sanctity_hull', shot:'wide', d:6.4, mus:'dread', cam:{z:1.16,y:.08}, to:{z:1.0,y:-.04}, sfx:['creak'],
  act:'CONCORD DREADNOUGHT SANCTITY. Two hundred guns. Painted the exact white of a thing that has never had to apologise.' },
{ sc:'square_tithe', shot:'wide', d:5.0, amb:['crowd'],
  act:'Nobody in the square runs. Running is what the second visit is for.' },
{ sc:'square_tithe', shot:'cu', who:'crier', em:'flat', d:7.2, chars:[{id:'crier',x:.5,y:.6,s:1}],
  line:"By order of the Meridian Concord, the harbour of Saltmarrow is called to Tithe. One part in five of all catch, all salt, all coin." },
{ sc:'square_tithe', shot:'cu', who:'crier', em:'cold', d:8.4,
  line:"Further. Possession of pirate colours, pirate cant, or pirate coin is treason against the mercy of God, and shall be answered on the spot." },
{ sc:'square_tithe', shot:'wide', d:4.0, mus:'dread',
  act:'On the spot. They put that in writing. Somebody wrote that down and thought it read well.' },
{ sc:'square_tithe', shot:'wide', d:5.4, sfx:['creak'], cam:{z:1.0}, to:{z:1.12},
  chars:[{id:'ardent',x:.62,y:.72,s:.55,fig:1}],
  act:'Commodore Vesk Ardent comes down the gangway without hurrying. He has never once had to hurry.' },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'calm', d:4.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Good morning. I would like this to be short." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'calm', d:6.4,
  line:"That is not a threat. Short is genuinely better for everyone. Long is where the paperwork starts." },
{ sc:'square_tithe', shot:'wide', d:5.0, mus:'tension', sfx:['wood'],
  act:'Soldiers go through Mama Dol\'s boat the way weather goes through a field.' },
{ sc:'square_tithe', shot:'insert', d:4.6, cam:{z:1.7}, to:{z:1.5}, sfx:['flagsnap'],
  act:'They come up with a scrap of black cloth. Hand-hemmed. Old. Knotted at one corner in a way that is not decorative.' },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'flat', d:3.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Whose is this." },
{ sc:'square_tithe', shot:'cu', who:'dol', em:'flat', d:2.4, chars:[{id:'dol',x:.5,y:.6,s:1}],
  line:"Mine." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'cold', d:2.8, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"It's a rag." },
{ sc:'square_tithe', shot:'cu', who:'dol', em:'bitter', d:3.0, chars:[{id:'dol',x:.5,y:.6,s:1}],
  line:"Then give it back." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'cold', d:8.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"It is a rag with a knot in it. The knot has a name. The name has a ship, and the ship has a hundred and forty counts against it. Your boat is forfeit." },
{ sc:'square_tithe', shot:'cu', who:'dol', em:'broken', d:4.0, chars:[{id:'dol',x:.5,y:.6,s:1}],
  line:"That boat is the whole of it. That's the whole of it, son." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'flat', d:3.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"I know. That's what makes it work." },
{ sc:'square_tithe', shot:'wide', d:4.2, mus:'tension', shake:.2,
  act:'And that is the exact moment Rook Vantier\'s mouth stops consulting the rest of him.' },
{ sc:'square_tithe', shot:'cu', who:'rook', em:'urgent', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"It's a sail patch." },
{ sc:'square_tithe', shot:'wide', d:3.4, sfx:['stinger'], shake:.35,
  act:'Six hundred people find something else to look at.' },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'flat', d:2.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Is it." },
{ sc:'square_tithe', shot:'cu', who:'rook', em:'determined', d:4.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I tied it. I'm bad at knots. Ask anyone here how bad I am at knots." },
{ sc:'square_tithe', shot:'two', d:5.4, mus:'dread', cam:{z:1.1}, to:{z:1.22},
  chars:[{id:'rook',x:.34,y:.66,s:.9},{id:'ardent',x:.66,y:.64,s:.9,flip:1,em:'cold'}],
  act:'Ardent looks at him. Not angry. Filing.' },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'calm', d:3.2, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"What's your name." },
{ sc:'square_tithe', shot:'cu', who:'nell', em:'urgent', d:5.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"He's nobody's, sir. He's the crane boy. He's slow." },
{ sc:'square_tithe', shot:'cu', who:'rook', em:'angry', d:2.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I'm not sl—" },
{ sc:'square_tithe', shot:'cu', who:'nell', em:'flat', d:2.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"He's slow." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'dry', d:4.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Mm. Take the boat. Leave the woman her nets." },
{ sc:'square_tithe', shot:'cu', who:'pike', em:'neutral', d:2.8, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"Sir — the standing order is total seizure." },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'cold', d:6.4, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"She has to eat, Lieutenant. A corpse can't be taxed. Mercy is arithmetic." },
{ sc:'square_tithe', shot:'wide', d:5.6, mus:'grief', amb:['wind'], cam:{z:1.14}, to:{z:1.0},
  act:'They take the boat. It goes out of the harbour under someone else\'s hand, which is the worst way a boat can leave.' },
{ sc:'square_tithe', shot:'cu', who:'ardent', em:'calm', d:5.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Thank you, Saltmarrow. You were short. I noticed." },

{ sc:'docks_day', shot:'two', d:4.6, mus:'grief', amb:['surf'],
  chars:[{id:'nell',x:.36,y:.64,s:.88},{id:'rook',x:.66,y:.66,s:.88,flip:1,em:'bitter'}],
  act:'Afterwards, on the empty end of the dock.' },
{ sc:'docks_day', shot:'cu', who:'rook', em:'angry', d:3.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Why'd you stop me." },
{ sc:'docks_day', shot:'cu', who:'nell', em:'flat', d:4.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Because I've buried enough people who were right." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'bitter', d:4.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"He took her whole life and said thank you." },
{ sc:'docks_day', shot:'cu', who:'nell', em:'sad', d:5.2, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Yeah. And in four days we'll be selling him fish. That's the town, Rook." },
{ sc:'docks_day', shot:'cu', who:'rook', em:'determined', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Come with me. I want to show you something." },
{ sc:'docks_day', shot:'cu', who:'nell', em:'dry', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Is it a body?" },
{ sc:'docks_day', shot:'cu', who:'rook', em:'grin', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"It's worse." },

{ sc:'seacave', shot:'wide', d:7.2, mus:'wonder', card:'THE UNDERCUT — LOW TIDE ONLY',
  sfx:['splash'], cam:{z:1.16,x:-.06}, to:{z:1.0,x:.04},
  act:'A cave under the point that is only a room for four hours a day.' },
{ sc:'seacave', shot:'wide', d:5.6, cam:{z:1.0}, to:{z:1.2},
  chars:[{id:'rook',x:.36,y:.8,s:.44,fig:1,pose:'point'},{id:'nell',x:.52,y:.82,s:.42,fig:1}],
  act:'And in it, propped on driftwood, three years of somebody\'s evenings.' },
{ sc:'seacave', shot:'cu', who:'nell', em:'shock', d:3.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"...What is that." },
{ sc:'seacave', shot:'cu', who:'rook', em:'warm', d:2.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"It's a ship." },
{ sc:'seacave', shot:'cu', who:'nell', em:'flat', d:3.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"It's a coffin with ambitions." },
{ sc:'seacave', shot:'cu', who:'rook', em:'grin', d:4.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"She's got a keel and a name. That's most of a ship." },
{ sc:'seacave', shot:'cu', who:'nell', em:'dry', d:2.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"What's the name." },
{ sc:'seacave', shot:'cu', who:'rook', em:'soft', d:2.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Nine." },
{ sc:'seacave', shot:'cu', who:'nell', em:'soft', d:3.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"...Why Nine." },
{ sc:'seacave', shot:'cu', who:'rook', em:'flat', d:3.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"How old I was when I decided." },
{ sc:'seacave', shot:'wide', d:5.0, mus:'wonder',
  act:'Nell walks the length of it with her hand flat on the strakes, the way she checks a winch. She does not say the thing she is thinking, which is that four of the joints are wrong.' },
{ sc:'seacave', shot:'cu', who:'nell', em:'flat', d:4.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Four of your joints are wrong." },
{ sc:'seacave', shot:'cu', who:'rook', em:'grin', d:2.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Only four?" },
{ sc:'seacave', shot:'cu', who:'nell', em:'dry', d:4.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Four that would kill you. The rest would just embarrass you." },
{ sc:'seacave', shot:'insert', d:5.2, mus:'mystery', sfx:['bell'], cam:{z:1.8}, to:{z:1.62},
  act:'And then she finds the compass, wrapped in oilcloth in the bow like something being kept warm.' },
{ sc:'seacave', shot:'cu', who:'nell', em:'awe', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"This is Concord brass. Where did you get this." },
{ sc:'seacave', shot:'cu', who:'rook', em:'soft', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"It was his. Hallow's." },
{ sc:'seacave', shot:'cu', who:'nell', em:'flat', d:4.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Hallow's a story people tell so the harbour feels bigger." },
{ sc:'seacave', shot:'cu', who:'rook', em:'flat', d:4.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"He existed. He bled on me." },
{ sc:'seacave', shot:'two', d:4.6, mus:'mystery',
  chars:[{id:'nell',x:.36,y:.64,s:.88,em:'soft'},{id:'rook',x:.66,y:.66,s:.88,flip:1,em:'flat'}],
  act:'She turns it over. There is a gull cut into the lid, badly, by hand, by somebody in a hurry.' },
{ sc:'seacave', shot:'cu', who:'nell', em:'soft', d:2.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Have you opened it?" },
{ sc:'seacave', shot:'cu', who:'rook', em:'flat', d:2.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"No." },
{ sc:'seacave', shot:'cu', who:'nell', em:'soft', d:2.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Rook. Why not." },
{ sc:'seacave', shot:'cu', who:'rook', em:'soft', d:7.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Because if it points at this town, then I have to be happy here. And I'd have to start today." },
{ sc:'seacave', shot:'wide', d:5.4, mus:'grief', cam:{z:1.0}, to:{z:1.12},
  act:'Nell puts it back in the oilcloth. Carefully. She has never once been careful with anything of his before.' },

{ sc:'harbor_night', shot:'wide', d:6.6, mus:'mystery', card:'THAT NIGHT', amb:['surf','wind'],
  sfx:[['bell',.6]], cam:{z:1.12,x:.05}, to:{z:1.0,x:-.03},
  act:'And at the back end of the middle watch, when the harbour light is the only honest thing awake, a ship comes in.' },
{ sc:'harbor_night', shot:'mid', d:5.8, cam:{z:1.35}, to:{z:1.5}, sfx:['creak'],
  act:'No lights. No customs pennant. No flag at all, which is its own kind of flag.' },
{ sc:'harbor_night', shot:'cu', who:'nell', em:'whisper', d:5.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"No colours. Nobody sails in dark unless they'd have to explain the colours." },
{ sc:'harbor_night', shot:'cu', who:'rook', em:'awe', d:4.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"That's the Ember Gull." },
{ sc:'harbor_night', shot:'cu', who:'nell', em:'flat', d:2.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"That's a story." },
{ sc:'harbor_night', shot:'cu', who:'rook', em:'determined', d:4.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"That's the story. With a hull." },
{ sc:'harbor_night', shot:'wide', d:6.0, mus:'tension', sfx:['creak'], cam:{z:1.0}, to:{z:1.18},
  act:'Rook is already walking. Nell says his name twice. The second one is louder and does exactly as much good as the first.' },

{ sc:'tavern', shot:'wide', d:6.4, mus:'warm', amb:['crowd','fire','room'], sfx:[['creak',.5]],
  card:'THE DROWNED DOG', cam:{z:1.08}, to:{z:1.0},
  act:'The Drowned Dog at two in the morning: eleven people, one fire, and the specific silence of a room that has decided not to have seen anything.' },
{ sc:'tavern', shot:'wide', d:5.6, mus:'tension', cam:{z:1.0}, to:{z:1.16},
  chars:[{id:'thorne',x:.56,y:.74,s:.5,fig:1},{id:'grit',x:.74,y:.76,s:.56,fig:1}],
  act:'The door opens on a woman in a coat too heavy for the season, with an iron brace on her left forearm and salt in her hair.' },
{ sc:'tavern', shot:'cu', d:4.6, chars:[{id:'thorne',x:.5,y:.6,s:1,em:'calm'}], mus:'tension',
  act:'Nobody in the Drowned Dog looks up. Every single person in the Drowned Dog knows exactly who just walked in.' },
{ sc:'tavern', shot:'wide', d:5.0, cam:{z:1.0}, to:{z:1.1},
  act:'And Rook Vantier, who has waited eight years and cannot manage another four seconds, stands up.' },
{ sc:'tavern', shot:'cu', who:'rook', em:'determined', d:3.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Take me with you." },
{ sc:'tavern', shot:'wide', d:5.0, sfx:['stinger'], shake:.3, mus:null,
  act:'Eleven people find something else to look at.' },

/* ══════════════════════ EYECATCH ══════════════════════ */
{ chap:'Eyecatch' },
{ sc:'black', shot:'wide', d:5.0, flash:.6, sfx:['stinger'], mus:'op',
  title:{l1:'BEYOND', l2:'THE REACH', sub:''} },
{ sc:'reach_night', shot:'wide', d:5.0, mus:'op', cam:{z:1.2}, to:{z:1.0} },

/* ══════════════════════ PART B ══════════════════════ */
{ chap:'Part B' },
{ sc:'tavern', shot:'wide', d:5.6, mus:'tension', amb:['crowd','fire','room'],
  chars:[{id:'thorne',x:.6,y:.74,s:.5,fig:1}],
  act:'Captain Iris Thorne takes her time about turning around. She is very good at making a room wait.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'flat', d:2.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Sit down." },
{ sc:'tavern', shot:'cu', who:'rook', em:'determined', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Take me with you." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'dry', d:4.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"You said that already. It didn't improve." },
{ sc:'tavern', shot:'cu', who:'grit', em:'laugh', d:4.2, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"He's got a voice on him though, Cap. That carried." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'flat', d:4.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"He's got a death on him, Grit. Different quality entirely." },
{ sc:'tavern', shot:'two', d:5.0, cam:{z:1.06}, to:{z:1.18},
  chars:[{id:'rook',x:.33,y:.66,s:.9,em:'determined'},{id:'thorne',x:.67,y:.64,s:.9,flip:1,em:'calm'}],
  act:'She crosses the room and looks at him properly, which is worse than being shouted at.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'calm', d:4.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"What do you think it is we do out there, boy?" },
{ sc:'tavern', shot:'cu', who:'rook', em:'flat', d:3.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"You go past the Reach." },
{ sc:'tavern', shot:'wide', d:4.4, sfx:['stinger'], mus:'dread', shake:.4,
  act:'Somewhere in the room, a chair leg moves half an inch and stops.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'cold', d:5.2, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"...And who exactly told you that we go past the Reach." },
{ sc:'tavern', shot:'cu', who:'rook', em:'soft', d:4.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Nobody. Nobody's ever told me anything. That's why I want to go." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'flat', d:6.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Hm. Listen to me, because I'm only going to be honest with you once." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'calm', d:7.6,
  line:"The sea doesn't want you. It has never wanted anybody. What it wants is whatever you'll hand over to get to it." },
{ sc:'tavern', shot:'wide', d:5.4, mus:'grief',
  chars:[{id:'grit',x:.3,y:.74,s:.56,fig:1},{id:'thorne',x:.6,y:.74,s:.5,fig:1}],
  act:'She does not gesture at her crew. She does not have to. Every one of them is missing something you can see from the door.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'flat', d:5.0, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Everyone behind me has paid. Go on. Ask one of them what for." },
{ sc:'tavern', shot:'cu', who:'grit', em:'warm', d:4.0, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"Don't ask me, lad. I'll tell you, and then you'll not sleep." },
{ sc:'tavern', shot:'cu', who:'rook', em:'determined', d:4.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I've got nothing anybody wants." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'bitter', d:5.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Then you've got nothing to trade, and this conversation is finished." },
{ sc:'tavern', shot:'wide', d:5.0, mus:'mystery', cam:{z:1.0}, to:{z:1.14},
  act:'So Rook puts the compass on the table.' },
{ sc:'tavern', shot:'insert', d:5.6, cam:{z:1.9}, to:{z:1.68}, sfx:['bell'], mus:'mystery',
  act:'Brass. Warm. A gull cut into the lid, badly, by hand, by somebody in a hurry.' },
{ sc:'tavern', shot:'cu', d:4.4, chars:[{id:'thorne',x:.5,y:.6,s:1,em:'shock'}], sfx:['heartbeat'],
  act:'Captain Thorne stops being amused.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'urgent', d:3.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Where did you get that." },
{ sc:'tavern', shot:'cu', who:'rook', em:'flat', d:8.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"A man gave it to me on the rocks under the light. Eight years ago. He was dying, and he was extremely rude about it." },
{ sc:'tavern', shot:'cu', d:4.6, chars:[{id:'thorne',x:.5,y:.6,s:1,em:'broken'}], mus:'grief',
  act:'And something very old goes through her face and does not come back out the other side.' },
{ sc:'tavern', shot:'cu', who:'thorne', em:'broken', d:3.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"...Elias." },
{ sc:'tavern', shot:'cu', who:'rook', em:'awe', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"You knew him." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'sad', d:8.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"He was my quartermaster. Then he was my captain. Then he was the reason I still have a crew." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'flat', d:3.2,
  line:"Have you opened it." },
{ sc:'tavern', shot:'cu', who:'rook', em:'flat', d:2.2, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"No." },
{ sc:'tavern', shot:'cu', who:'thorne', em:'urgent', d:5.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Good. Don't. Not in a room. Not with a roof on it." },
{ sc:'tavern', shot:'cu', who:'rook', em:'urgent', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Why not—" },

{ sc:'tavern_raid', shot:'wide', d:2.4, mus:'battle', sfx:['wood'], flash:.9, shake:1,
  act:'' },
{ sc:'tavern_raid', shot:'wide', d:3.4, sfx:['musket'], shake:.8, amb:['crowd'],
  act:'The door comes off its hinges and into the room, which is a thing doors are not supposed to do.' },
{ sc:'tavern_raid', shot:'cu', who:'pike', em:'shout', d:3.6, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"CONCORD! NOBODY MOVES!" },
{ sc:'tavern_raid', shot:'wide', d:4.0, mus:'battle', sfx:['clash'], shake:.6, speed:.8,
  chars:[{id:'grit',x:.3,y:.74,s:.58,fig:1,pose:'sword'},{id:'thorne',x:.62,y:.74,s:.5,fig:1,pose:'sword'}],
  act:'Everybody moves.' },
{ sc:'tavern_raid', shot:'cu', who:'thorne', em:'shout', d:3.0, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"GRIT — THE BACK WALL IS A DOOR NOW!" },
{ sc:'tavern_raid', shot:'cu', who:'grit', em:'roar', d:2.8, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"AYE THAT!" },
{ sc:'tavern_raid', shot:'wide', d:3.0, sfx:['wood'], shake:.9, flash:.4,
  act:'It is a door now.' },
{ sc:'tavern_raid', shot:'cu', who:'nell', em:'yell', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"ROOK. ROOK! ROOF!" },
{ sc:'tavern_raid', shot:'cu', who:'rook', em:'breathless', d:2.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"You followed me?!" },
{ sc:'tavern_raid', shot:'cu', who:'nell', em:'yell', d:3.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"OBVIOUSLY I FOLLOWED YOU!" },

{ sc:'roofs_night', shot:'wide', d:4.2, mus:'battle', amb:['wind'], sfx:['whoosh'], speed:1, cam:{z:1.3,x:-.1}, to:{z:1.0,x:.1},
  chars:[{id:'rook',x:.4,y:.7,s:.5,fig:1,pose:'reach'},{id:'nell',x:.56,y:.72,s:.46,fig:1}],
  act:'Saltmarrow from the top: two hundred roofs, forty washing lines, and one route across that only two people have ever bothered to learn.' },
{ sc:'roofs_night', shot:'wide', d:3.2, sfx:['musket'], flash:.4, shake:.6, speed:.7,
  act:'' },
{ sc:'roofs_night', shot:'cu', who:'nell', em:'breathless', d:3.8, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"They're shooting at us! On a Tuesday!" },
{ sc:'roofs_night', shot:'cu', who:'rook', em:'breathless', d:3.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Is Tuesday relevant?!" },
{ sc:'roofs_night', shot:'cu', who:'nell', em:'yell', d:3.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"IT IS TO ME!" },
{ sc:'roofs_night', shot:'wide', d:4.4, sfx:['whoosh'], speed:1, shake:.4,
  chars:[{id:'rook',x:.46,y:.68,s:.5,fig:1,pose:'reach'}],
  act:'The gap over Cutter\'s Lane is nine feet. They have both done it drunk. Neither of them has done it shot at.' },
{ sc:'roofs_night', shot:'wide', d:3.6, mus:'tension', sfx:['chain'], cam:{z:1.0}, to:{z:1.2},
  act:'And then, from the harbour, a sound that stops both of them dead.' },
{ sc:'dock_confront', shot:'wide', d:5.6, mus:'dread', sfx:['chain'], amb:['surf','wind'],
  cam:{z:1.16}, to:{z:1.0},
  act:'The harbour chain. Four tons of it, coming up out of the water across the mouth of the bay.' },
{ sc:'dock_confront', shot:'cu', who:'nell', em:'fear', d:4.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"They've raised the chain. Nothing gets out. Nothing has ever got out." },

{ sc:'dock_confront', shot:'wide', d:5.4, mus:'dread', cam:{z:1.0}, to:{z:1.12},
  chars:[{id:'ardent',x:.7,y:.72,s:.5,fig:1},{id:'thorne',x:.34,y:.72,s:.5,fig:1}],
  act:'On the dock, two people who have not stood this close since a night nobody in the Concord is allowed to write down.' },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'calm', d:2.6, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Iris." },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'flat', d:2.4, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Vesk." },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'dry', d:4.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"You look well, for a woman I buried at sea." },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'dry', d:4.2, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"You look tired, for a man who won." },
{ sc:'dock_confront', shot:'two', d:5.2, mus:'grief',
  chars:[{id:'thorne',x:.32,y:.64,s:.9,em:'flat'},{id:'ardent',x:.68,y:.64,s:.9,flip:1,em:'sad'}],
  act:'Neither of them reaches for anything. That is the part the young ones watching do not understand.' },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'sad', d:4.4, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"You were the best of us. You know that." },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'bitter', d:5.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"That's how I found out what we were." },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'cold', d:5.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Strike your sails and I'll try you in a court. That is a genuine offer, and it is the last one." },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'flat', d:5.0, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Vesk. There's no court on the far side of that wall." },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'cold', d:4.4, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"There is nothing on the far side of that wall." },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'soft', d:4.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Then why have you got two hundred guns pointed at a woman who wants to go and look?" },
{ sc:'dock_confront', shot:'wide', d:4.4, mus:'dread', cam:{z:1.0}, to:{z:1.14},
  act:'Ardent does not answer. Ardent has never once answered that.' },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'flat', d:3.2, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Lieutenant. Sanctity may fire." },
{ sc:'dock_confront', shot:'cu', who:'pike', em:'fear', d:3.4, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"Sir, the town's inside the arc—" },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'cold', d:3.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Sanctity may fire." },
{ sc:'dock_confront', shot:'wide', d:3.0, mus:'battle', sfx:['cannon'], flash:.85, shake:1,
  act:'' },
{ sc:'dock_confront', shot:'wide', d:4.0, sfx:[['cannon',.1],['splash',.6],['wood',.9]], shake:.9, flash:.4,
  act:'The first broadside takes the end of the fish market and most of a hundred-year-old argument about where the market should be.' },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'shout', d:3.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"GET HER OFF THE WALL! GRIT, CUT US LOOSE!" },
{ sc:'dock_confront', shot:'cu', who:'grit', em:'roar', d:4.0, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"CAP, WE'RE ON THE CHAIN! WE'RE SITTING ON IT!" },
{ sc:'dock_confront', shot:'wide', d:4.6, mus:'battle', sfx:['chain'], shake:.5,
  act:'The Ember Gull is pinned against four tons of iron with two hundred guns finding their range, and there is exactly one machine in Saltmarrow that can lift that chain.' },
{ sc:'crane_top', shot:'wide', d:4.6, mus:'battle', cam:{z:1.2,y:.1}, to:{z:1.0,y:0},
  act:'It is a hundred and ten feet of harbour crane, and Rook Vantier has climbed it drunk, twice, on a dare.' },
{ sc:'roofs_night', shot:'cu', who:'nell', em:'yell', d:5.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Rook — no. That's a hundred feet of open ladder under live fire—" },
{ sc:'roofs_night', shot:'cu', who:'rook', em:'determined', d:3.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Then don't watch." },
{ sc:'roofs_night', shot:'cu', who:'nell', em:'broken', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"That's not — that's not how watching works!" },

{ sc:'crane_top', shot:'wide', d:5.0, mus:'battle', sfx:['whoosh'], speed:1, shake:.4, cam:{z:1.0}, to:{z:1.18},
  chars:[{id:'rook',x:.44,y:.62,s:.5,fig:1,pose:'reach'}],
  act:'He goes up it like something being chased, because he is.' },
{ sc:'crane_top', shot:'wide', d:3.4, sfx:['cannon'], flash:.7, shake:1, act:'' },
{ sc:'crane_top', shot:'wide', d:4.6, sfx:[['clash',.2]], shake:.7,
  act:'A round takes the jib forty feet under him and the whole tower rings like a struck bell.' },
{ sc:'crane_top', shot:'cu', who:'rook', em:'breathless', d:4.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Okay. Okay. You wanted a big life." },
{ sc:'crane_top', shot:'cu', who:'rook', em:'determined', d:4.0, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"This is what one looks like from inside." },
{ sc:'crane_top', shot:'wide', d:5.0, mus:'battle', cam:{z:1.3,rot:-3}, to:{z:1.1,rot:2},
  act:'At the top of the crane is the counterweight: eleven tons of pig iron on a pin, held there by one shackle and the assumption that nobody would ever be stupid enough.' },
{ sc:'crane_top', shot:'cu', who:'rook', em:'determined', d:3.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Sorry, Nell. Four of my joints are wrong." },
{ sc:'crane_top', shot:'wide', d:2.6, sfx:['clash'], flash:.6, shake:.8, speed:1, act:'' },
{ sc:'crane_top', shot:'wide', d:4.4, sfx:[['chain',.1],['splash',1.1]], shake:1,
  act:'Eleven tons goes down. The jib comes round. And the harbour chain comes up out of the water like something being landed.' },
{ sc:'dock_confront', shot:'cu', who:'nell', em:'urgent', d:4.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"The winch pin! It'll hold at the pin — GRIT, THE PIN!" },
{ sc:'dock_confront', shot:'cu', who:'grit', em:'roar', d:3.0, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"WHICH PIN, GIRL!" },
{ sc:'dock_confront', shot:'cu', who:'nell', em:'yell', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"THE ONLY ONE I'VE EVER FIXED!" },
{ sc:'dock_confront', shot:'wide', d:3.6, sfx:['musket'], flash:.5, shake:.6,
  act:'She shoots it. She has never fired a gun in her life, and she has rebuilt that winch eleven times, and she knows exactly where it is weakest.' },
{ sc:'dock_confront', shot:'wide', d:4.6, mus:'resolve', sfx:[['chain',.05],['splash',.7]], shake:.9, flash:.35,
  act:'Four tons of chain goes into the harbour. The mouth of the bay is open for the first time in nineteen years.' },
{ sc:'dock_confront', shot:'cu', who:'thorne', em:'shout', d:3.2, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"EVERY SAIL SHE HAS! GO!" },
{ sc:'dock_confront', shot:'wide', d:4.4, mus:'resolve', sfx:['flagsnap'], cam:{z:1.0}, to:{z:1.2},
  act:'And two people go off the end of the crane arm into the water beside a moving ship, which is a much shorter drop than it sounds and a much worse one than it looks.' },
{ sc:'gull_deck', shot:'wide', d:4.6, sfx:['splash'], mus:'resolve', amb:['sea','wind'],
  act:'They get hauled over the rail by a man the size of a door.' },
{ sc:'gull_deck', shot:'cu', who:'grit', em:'laugh', d:4.4, chars:[{id:'grit',x:.5,y:.6,s:1}],
  line:"Two of 'em, Cap! One's soaked and one's furious!" },
{ sc:'gull_deck', shot:'cu', who:'nell', em:'breathless', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"I'm both. I'm both of those." },
{ sc:'gull_deck', shot:'wide', d:5.0, mus:'grief', cam:{z:1.06}, to:{z:1.16},
  chars:[{id:'thorne',x:.56,y:.72,s:.52,fig:1}],
  act:'Thorne comes down the deck with one hand pressed under her ribs and a great deal of the night on her coat.' },
{ sc:'gull_deck', shot:'cu', who:'thorne', em:'tired', d:3.0, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"You're not crew." },
{ sc:'gull_deck', shot:'cu', who:'rook', em:'breathless', d:2.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I know." },
{ sc:'gull_deck', shot:'cu', who:'thorne', em:'dry', d:3.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"You're cargo that argues." },
{ sc:'gull_deck', shot:'cu', who:'rook', em:'grin', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"I'll take it." },
{ sc:'gull_deck', shot:'two', d:5.2, mus:'resolve',
  chars:[{id:'rook',x:.34,y:.66,s:.9,em:'awe'},{id:'thorne',x:.68,y:.64,s:.9,flip:1,em:'flat'}],
  act:'She pulls a bundle out of her coat. Black cloth, folded the way you fold something you have carried a long way.' },
{ sc:'gull_deck', shot:'cu', who:'thorne', em:'flat', d:5.6, chars:[{id:'thorne',x:.5,y:.6,s:1}],
  line:"Elias made this one. It's the last of his." },
{ sc:'gull_deck', shot:'cu', who:'thorne', em:'determined', d:5.4,
  line:"If you're going to die for it — then you carry it." },
{ sc:'gull_deck', shot:'wide', d:5.0, mus:'resolve', cam:{z:1.14}, to:{z:1.0}, sfx:['creak'],
  chars:[{id:'rook',x:.5,y:.72,s:.5,fig:1,pose:'reach'}],
  act:'And Rook Vantier, seventeen, soaked, bleeding from somewhere he has not found yet, goes up the mainmast in the dark.' },
{ sc:'gull_deck_flag', shot:'wide', d:6.4, mus:'resolve', sfx:['flagsnap'], flash:.45, cam:{z:1.3}, to:{z:1.0},
  act:'' },
{ sc:'gull_deck_flag', shot:'wide', d:6.0, mus:'resolve', cam:{z:1.0,y:-.04}, to:{z:1.12,y:.02},
  act:'The colours go up over Saltmarrow harbour for the first time in nineteen years, and about two hundred people who were pretending to be asleep get out of bed to watch.' },

{ sc:'dock_confront', shot:'wide', d:5.4, mus:'dread', amb:['surf','wind'],
  chars:[{id:'ardent',x:.6,y:.72,s:.5,fig:1},{id:'pike',x:.76,y:.74,s:.46,fig:1}],
  act:'On the dock, Commodore Ardent watches a black flag leave his harbour and does not give a single order.' },
{ sc:'dock_confront', shot:'cu', who:'pike', em:'urgent', d:4.0, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"Sir — we can still take her in the channel. Sir?" },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'flat', d:2.4, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"No." },
{ sc:'dock_confront', shot:'cu', who:'pike', em:'shock', d:2.6, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"Sir, with respect—" },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'cold', d:5.4, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Signal the Admiralty. Priority of the first order, my authority." },
{ sc:'dock_confront', shot:'cu', who:'pike', em:'neutral', d:2.6, chars:[{id:'pike',x:.5,y:.6,s:1}],
  line:"Wording, sir?" },
{ sc:'dock_confront', shot:'cu', d:3.2, chars:[{id:'ardent',x:.5,y:.6,s:1,em:'sad'}], mus:'dread',
  act:'A very long pause on a very cold dock.' },
{ sc:'dock_confront', shot:'cu', who:'ardent', em:'cold', d:6.0, chars:[{id:'ardent',x:.5,y:.6,s:1}],
  line:"Tell them Hallow's compass has woken up. They'll know what it costs." },
{ sc:'dock_confront', shot:'wide', d:5.0, mus:'dread', sfx:['stinger'], cam:{z:1.0}, to:{z:1.18},
  act:'Lieutenant Pike does not know what it costs. He writes it down anyway, because that is what the Concord is.' },

{ sc:'open_sea_dawn', shot:'wide', d:6.6, mus:'wonder', amb:['sea','wind'], sfx:['gull'],
  card:'FOUR HOURS OUT', cam:{z:1.1,x:.05}, to:{z:1.0,x:-.04},
  act:'Dawn, four hours west, with the town gone under the curve of the world and the wall of light standing up ahead of them like a held note.' },
{ sc:'open_sea_dawn', shot:'cu', who:'nell', em:'tired', d:5.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"I left the winch keys in my other coat. I keep thinking about the winch keys." },
{ sc:'open_sea_dawn', shot:'cu', who:'rook', em:'soft', d:2.8, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Nell." },
{ sc:'open_sea_dawn', shot:'cu', who:'nell', em:'sad', d:4.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"I know. I'm getting there. Give me till noon." },
{ sc:'open_sea_dawn', shot:'two', d:5.0, mus:'wonder',
  chars:[{id:'nell',x:.34,y:.64,s:.88,em:'tired'},{id:'rook',x:.68,y:.66,s:.88,flip:1,em:'soft'}],
  act:'They sit with their backs against the rail, the way you do when your legs have finished deciding things for you.' },
{ sc:'open_sea_dawn', shot:'cu', who:'nell', em:'soft', d:3.6, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Open it." },
{ sc:'open_sea_dawn', shot:'cu', who:'rook', em:'fear', d:2.6, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"Now?" },
{ sc:'open_sea_dawn', shot:'cu', who:'nell', em:'flat', d:5.0, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"You've got no town to be happy in any more. Seems like the safe time." },
{ sc:'open_sea_dawn', shot:'insert', d:5.6, mus:'mystery', sfx:['bell'], cam:{z:1.9}, to:{z:1.7},
  act:'The lid comes up with a sound like a small door in a large house.' },
{ sc:'open_sea_dawn', shot:'insert', d:5.4, cam:{z:1.7}, to:{z:1.9}, mus:'mystery',
  act:'The needle spins. It spins for a long time — longer than a needle has any right to.' },
{ sc:'open_sea_dawn', shot:'insert', d:4.6, sfx:['heartbeat'], cam:{z:1.9}, to:{z:2.1},
  act:'And then it stops.' },
{ sc:'open_sea_dawn', shot:'cu', d:4.0, chars:[{id:'rook',x:.5,y:.6,s:1,em:'shock'}], sfx:['stinger'],
  act:'Dead west. Not at the ship. Not at the girl beside him. Not back at the town.' },
{ sc:'reach_dawn', shot:'wide', d:6.4, mus:'resolve', sfx:['whoosh'], flash:.4, cam:{z:1.4}, to:{z:1.0},
  act:'Dead west, at two hundred miles of standing water that everybody in the world agrees is the end of everything.' },
{ sc:'open_sea_dawn', shot:'cu', who:'rook', em:'awe', d:3.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"...Oh." },
{ sc:'open_sea_dawn', shot:'cu', who:'nell', em:'fear', d:3.4, chars:[{id:'nell',x:.5,y:.6,s:1}],
  line:"Rook. Rook, what does that mean." },
{ sc:'open_sea_dawn', shot:'cu', who:'rook', em:'soft', d:4.4, chars:[{id:'rook',x:.5,y:.6,s:1}],
  line:"It means he wasn't lying about any of it." },
{ sc:'reach_dawn', shot:'wide', d:7.0, mus:'wonder', cam:{z:1.0}, to:{z:1.14}, who:'vo', em:'soft',
  line:"Here's the thing nobody tells you about wanting something your whole life." },
{ sc:'reach_dawn', shot:'wide', d:6.6, cam:{z:1.14}, to:{z:1.3}, who:'vo', em:'soft',
  line:"It's very quiet when it finally starts." },
{ sc:'black', shot:'wide', d:3.4, mus:null, sfx:['stinger'], act:'' },

/* ══════════════════════ ENDING ══════════════════════ */
{ chap:'Ending' },
{ sc:'ed_sea', shot:'wide', d:14.0, mus:'ed', amb:['sea','wind'], cam:{z:1.1,x:-.05}, to:{z:1.0,x:.04},
  title:{l1:'', l2:'', sub:'BEYOND THE REACH'} },
{ sc:'ed_sea', shot:'wide', d:13.0, cam:{z:1.0,x:.04}, to:{z:1.08,x:-.04},
  title:{l1:'', l2:'', sub:'EPISODE 1 · RAISE YOUR COLORS'} },
{ sc:'ed_sea', shot:'wide', d:13.0, cam:{z:1.08,y:.03}, to:{z:1.0,y:-.03},
  title:{l1:'', l2:'', sub:'ROOK VANTIER · NELL OSTRAND · IRIS THORNE · VESK ARDENT'} },
{ sc:'ed_sea', shot:'wide', d:13.0, cam:{z:1.0}, to:{z:1.12},
  title:{l1:'', l2:'', sub:'ELIAS HALLOW · MAMA DOL · BOSUN GRIT · LT. PIKE'} },
{ sc:'ed_sea', shot:'wide', d:12.0, cam:{z:1.12,x:.04}, to:{z:1.0,x:-.05},
  title:{l1:'', l2:'', sub:'THE SEA DOES NOT END'} },

/* ══════════════════════ NEXT EPISODE ══════════════════════ */
{ chap:'Next Episode' },
{ sc:'reach_night', shot:'wide', d:5.0, mus:'tension', amb:['sea','wind'], flash:.4,
  who:'vo', em:'determined',
  line:"Next time, on Beyond the Reach." },
{ sc:'storm_sea', shot:'wide', d:5.4, sfx:['thunder'], shake:.5, who:'vo', em:'urgent',
  line:"The wall has a door. The door has a price." },
{ sc:'gull_deck', shot:'wide', d:5.0, sfx:['creak'], who:'vo', em:'flat',
  line:"And Nell finds out what I traded to get us through it." },
{ sc:'black', shot:'wide', d:4.6, sfx:['stinger'], flash:.5, mus:'op',
  title:{l1:'EPISODE TWO', l2:'', sub:'THE SEA THAT SAYS YOUR NAME'} }

  ]
};
